name: FDTsFarmWithExp
main: onl.fdt.java.minecraft.spigot.FDTsFarmWithExp.PluginMain
version: 2.0
commands:
  fdtsfarmwithexp:
    usage: /fdtsfarmwithexp <setExpAmount|registerExpBlock|unregisterExpBlock>
